### ISSUE TITLE
ARM architecture not supported

### ISSUE THREAD

**Issue by Stadicus** [altangent/lnd-explorer#2]
Unfortunately, Node Sass does not support ARM architecture, which excludes most micro-computers (like Raspberry Pi) from using your project. 

I would love to use your lnd-explorer in my Lightning Guide:
https://medium.com/@stadicus/perfect-low-cost-%EF%B8%8Flightning%EF%B8%8F-node-4c2f42a4ff7b

Any chance that this could be fixed?

Errors when installing on a Hardkernel Odroid HC2
http://www.hardkernel.com/main/products/prdt_info.php

```
Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 8.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.7.2
    at module.exports (/home/admin/download/lnd-explorer/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/admin/download/lnd-explorer/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/admin/download/lnd-explorer/node_modules/node-sass/bin/node-sass:10:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by bmancini55** [comment]
I'll take a look at it today and see if we can come up with a solution.    Thanks for submitting the issue!

**Comment by coretechs** [comment]
I am unable to reproduce this problem on a clean system.

I'm using an Odroid-XU4 (same CPU as HC2) with a fresh install of the Ubuntu server image provided by hardkernel + latest updates applied, kernel version 4.14.5-92.

Installed build-essential & git from default apt sources, installed nodejs 8.9.4 from nodesource using install scripts (https://nodejs.org/en/download/package-manager/), cloned lnd-explorer and ran `npm install && npm run build && npm start`

I verified that node-sass@4.7.2 is installed and working properly and verified that the complied app.css is accessible on the webserver.

Can you provide any other information and/or try running `npm rebuild node-sass`?

**Comment by Stadicus** [comment]
I just tried again. With `npm rebuild node-sass` I get the error message that "python" or "python2" could not be found in the path. Not sure what packages (apt or npm) to install, or just to set the path correctly...

My config:
Linux kernel 4.14.20-108
Node.js v8.10.0

When trying the `build` again:
```
$ sudo npm run build

> lnd-explorer@1.0.0 build /home/admin/download/lnd-explorer
> npm-run-all build:*


> lnd-explorer@1.0.0 build:app /home/admin/download/lnd-explorer
> NODE_ENV=production browserify src/client/app.jsx --extension=.jsx -o ./dist/app/bundle.js


> lnd-explorer@1.0.0 build:app-compress /home/admin/download/lnd-explorer
> uglifyjs -c -o ./dist/app/bundle.js ./dist/app/bundle.js


> lnd-explorer@1.0.0 build:scss /home/admin/download/lnd-explorer
> node-sass -o dist/css --output-style compressed src/scss/app.scss

/home/admin/download/lnd-explorer/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 8.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.7.2
    at module.exports (/home/admin/download/lnd-explorer/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/admin/download/lnd-explorer/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/admin/download/lnd-explorer/node_modules/node-sass/bin/node-sass:10:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lnd-explorer@1.0.0 build:scss: `node-sass -o dist/css --output-style compressed src/scss/app.scss`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lnd-explorer@1.0.0 build:scss script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2018-03-10T14_49_39_752Z-debug.log
ERROR: "build:scss" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lnd-explorer@1.0.0 build: `npm-run-all build:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lnd-explorer@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2018-03-10T14_49_39_815Z-debug.log
```

Debug log:
```
cat /home/admin/.npm/_logs/2018-03-10T14_49_39_815Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.7.1
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle lnd-explorer@1.0.0~prebuild: lnd-explorer@1.0.0
6 info lifecycle lnd-explorer@1.0.0~build: lnd-explorer@1.0.0
7 verbose lifecycle lnd-explorer@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle lnd-explorer@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/admin/download/lnd-explorer/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle lnd-explorer@1.0.0~build: CWD: /home/admin/download/lnd-explorer
10 silly lifecycle lnd-explorer@1.0.0~build: Args: [ '-c', 'npm-run-all build:*' ]
11 silly lifecycle lnd-explorer@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle lnd-explorer@1.0.0~build: Failed to exec build script
13 verbose stack Error: lnd-explorer@1.0.0 build: `npm-run-all build:*`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid lnd-explorer@1.0.0
15 verbose cwd /home/admin/download/lnd-explorer
16 verbose Linux 4.14.20-108
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.10.0
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error lnd-explorer@1.0.0 build: `npm-run-all build:*`
22 error Exit status 1
23 error Failed at the lnd-explorer@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by coretechs** [comment]
You need to have python in order to build node-sass.

Can you run `python --version` and/or `which python` and ensure it is installed and that the path is correct?  The odroid I'm using for testing has Python 2.7.12 installed.

**Comment by Stadicus** [comment]
Sorry for the lack of any response, I am heavily focused on my Raspberry Pi project at the moment and currently do not have a running Odroid setup. Please bear with me, I will pick this up again. Thanks for your patience!

**Comment by jsgoyette** [comment]
For what it's worth, I ran into this problem on an Odriod and was able to get it working by manually making the changes included in this yet unmerged pull request for the node-sass repo:

https://github.com/sass/node-sass/pull/2253/files

**Comment by Stadicus** [comment]
On a new try, it actually worked on the Raspberry Pi with the following commands:

```
$ git clone https://github.com/altangent/lnd-explorer
$ cd lnd-explorer
$ npm install
$ npm audit
$ npm audit fix
$ npm run build
$ npm start
```
