### ISSUE TITLE
Unhandled error in GRPC calls

### ISSUE THREAD

**Issue by whizz** [altangent/lnd-explorer#6]
It looks like the app does not handle the error event when connection to lnd fails for some reason.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: 14 UNAVAILABLE: EOF
    at createStatusError (/opt/lnd-explorer/node_modules/grpc/src/client.js:65:15)
    at ClientReadableStream._emitStatusIfDone (/opt/lnd-explorer/node_modules/grpc/src/client.js:271:19)
    at ClientReadableStream._receiveStatus (/opt/lnd-explorer/node_modules/grpc/src/client.js:249:8)
    at /opt/lnd-explorer/node_modules/grpc/src/client.js:715:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lnd-explorer@1.1.0 start: `NODE_ENV=production node src/server/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lnd-explorer@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by bmancini55** [comment]
Interesting.  Any steps to repro this?  

If I shut down LND and attempt to access a page I get an error, but not an unhandled event exception.
```
error:  Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/Users/bmancini/code/go/src/altangent/lnd-explorer/node_modules/grpc/src/client.js:65:15)
    at /Users/bmancini/code/go/src/altangent/lnd-explorer/node_modules/grpc/src/client.js:568:15
```
